Neos:
  Neos:
    fusion:
      autoInclude:
        Neos.Presentation: true
  Flow:
    mvc:
      routes:
        'Sitegeist.Monocle':
          position: 'start 1'

Sitegeist:
  Monocle:
    hiddenPrototypeNamePatterns:
      - 'Sitegeist.Kaleidoscope:*'
    alwaysShowPrototypes: {  }
